server:
  port: 8081

#multi database config
spring:
  datasource:
    mysql:
      main:
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  #        url: jdbc:log4jdbc:mysql://mydb.cyqagiaocgni.ap-northeast-2.rds.amazonaws.com:33066/mydb
        jdbc-url: jdbc:log4jdbc:mysql://mydb.cyqagiaocgni.ap-northeast-2.rds.amazonaws.com:33066/mydb
        username: wowmin
        password: '!Dmssk6480'
      sub:
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        #        url: jdbc:log4jdbc:mysql://mydb.cyqagiaocgni.ap-northeast-2.rds.amazonaws.com:33066/mydb
        jdbc-url: jdbc:log4jdbc:mysql://ezen-test.ckwpj5qv8mu7.ap-northeast-2.rds.amazonaws.com:33065/tasteZip
        username: Himmel
        password: tKdldnjfem18!#

#  spring.master.datasource.driver-class-name=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#spring.master.datasource.jdbc-url=jdbc:log4jdbc:mysql://192.168.0.10:3306/MASTER?characterEncoding=UTF-8&serverTimezone=UTC
#spring.master.datasource.username={user name}
#spring.master.datasource.password={password}
#spring.master.datasource.connection-test-query=SELECT 1
#
#spring.slave-1.datasource.driver-class-name=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#spring.slave-1.datasource.jdbc-url=jdbc:log4jdbc:mysql://192.168.0.13:3306/SLAVE?characterEncoding=UTF-8&serverTimezone=UTC
#spring.slave-1.datasource.username={user name}
#spring.slave-1.datasource.password={password}
#spring.slave-1.datasource.connection-test-query=SELECT 1



#mybatis:
#  mapper-locations: classpath:/mybatis/mapper/infra/*.xml

#single database config
#spring:
#  datasource:
##    driver-class-name: com.mysql.cj.jdbc.Driver     # for query log by Tony 12.29
#    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
##    url: jdbc:mysql://mydb.cyqagiaocgni.ap-northeast-2.rds.amazonaws.com:33066/mydb     # for query log by Tony 12.29
#    url: jdbc:log4jdbc:mysql://mydb.cyqagiaocgni.ap-northeast-2.rds.amazonaws.com:33066/mydb
#    username: wowmin
#    password: '!Dmssk6480'
#
#mybatis:
#  mapper-locations: classpath:/mybatis/mapper/infra/*.xml
