version: 0.0
os: linux

files:
  - source: /
    destination: /home/centos/deploy
permissions:
  - object: /home/centos/deploy
    pattern: "**"
    owner: centos
    group: centos
    mode: 755
hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 120
      runas: centos